// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApp.Models;

#nullable disable

namespace WebApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241106105102_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("WebApp.Models.ContactEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("phone");

                    b.HasKey("Id");

                    b.ToTable("contacts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateOnly(2000, 12, 13),
                            Category = 0,
                            Created = new DateTime(2024, 11, 6, 11, 51, 1, 576, DateTimeKind.Local).AddTicks(1842),
                            Email = "asd@asd.asd",
                            FirstName = "Adam",
                            LastName = "Kowal",
                            PhoneNumber = "123 123 123"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateOnly(1999, 5, 5),
                            Category = 0,
                            Created = new DateTime(2024, 11, 6, 11, 51, 1, 576, DateTimeKind.Local).AddTicks(1883),
                            Email = "afdsfsdf@afdsfsdf.asd",
                            FirstName = "asd",
                            LastName = "Kfdsfds",
                            PhoneNumber = "555 123 123"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
